# Newest Python >= 3.11 on PATH (an older system python3 may come first);
# tools/repoctl applies the same rule for hooks. Override with PYTHON=...
PYTHON ?= $(shell for p in python3.14 python3.13 python3.12 python3.11 python3 python; do command -v $$p >/dev/null 2>&1 && $$p -c 'import sys; sys.exit(sys.version_info < (3, 11))' 2>/dev/null && { echo $$p; break; }; done)
REPOCTL := $(PYTHON) tools/repoctl.py
# This kit's directory, also when run from another repository with make -f (make adopt).
KIT_DIR := $(patsubst %/,%,$(dir $(abspath $(firstword $(MAKEFILE_LIST)))))
SKILL_TEST_SUITES := $(wildcard .agents/skills/*/tests)

.DEFAULT_GOAL := help

.PHONY: python-check test test-future verify done

python-check:
	@test -n "$(PYTHON)" && $(PYTHON) -c 'import sys; sys.exit(sys.version_info < (3, 11))' 2>/dev/null || { echo "Needs Python 3.11+ (found: '$(PYTHON)'); install python3.11 or newer, or run: make PYTHON=/path/to/python3.11 ..." >&2; exit 1; }

test: python-check
	$(PYTHON) -m unittest discover -s tools/tests -p 'test_*.py'
	@for suite in $(SKILL_TEST_SUITES); do \
	  echo "-- $$suite"; \
	  $(PYTHON) -m unittest discover -s "$$suite" -p 'test_*.py' || exit 1; \
	done

# The same suite 800 days ahead: fails when a fixture or check rots with the calendar (#10).
test-future: python-check
	PYTHONPATH="$(CURDIR)/tools/tests/clockshift" SHIFT_DAYS=800 $(MAKE) test

verify: python-check
	$(MAKE) test
	$(REPOCTL) verify
	$(REPOCTL) doctor

# The one completion command: heal derived files, run the change gate, then
# everything CI runs. Prints the risk tier so the right review follows.
done: python-check
	@$(REPOCTL) sync
	@$(REPOCTL) finish
	@$(MAKE) --no-print-directory verify
	@echo "All gates passed. Get the review your risk tier requires, then hand over or open the PR."

# Every repoctl command, generated by `make sync` from its @command declaration
# (tools/kit/commands.py and .agents/commands/). Make variables reach repoctl as
# quoted data, never as shell source. Edit the declaration, not this block.
# <repoctl:commands>
.PHONY: start next where ui-review new similar capabilities risk handover map garden sync issue review-packet incident init adopt kit-update check doctor readiness inventory resources skill-digest validate labels github-sync eval trial help

start: python-check
	@$(REPOCTL) start

next: python-check
	@$(REPOCTL) next

where: python-check
	$(if $(Q),,$(error Add what to look for: make where Q="login form"))
	@$(REPOCTL) where "$${Q}"

ui-review: python-check
	@$(REPOCTL) ui-review

new: python-check
	$(if $(KIND),,$(error Choose what to create: make new KIND=skill|agent|doc|rule|check|command|mcp|pack NAME=my-name DESC="what it does; when to use it"))
	$(if $(NAME),,$(error Name it: NAME=kebab-case-name))
	$(if $(DESC),,$(error Describe it: DESC="what it does; when to use it"))
	@$(REPOCTL) new $(if $(KIND),--kind "$${KIND}",) $(if $(NAME),--name "$${NAME}",) $(if $(DESC),--description "$${DESC}",) $(if $(PACK),--pack "$${PACK}",) $(if $(GROUP),--group "$${GROUP}",) $(if $(COVERS),--covers "$${COVERS}",) $(if $(ACCESS),--access "$${ACCESS}",) $(if $(TIER),--tier "$${TIER}",) $(if $(filter 1 yes true,$(FORCE)),--force,)

similar: python-check
	$(if $(Q),,$(error Describe the capability: make similar Q="draft release notes"))
	@$(REPOCTL) similar "$${Q}"

capabilities: python-check
	@$(REPOCTL) capabilities

risk: python-check
	@$(REPOCTL) risk

handover: python-check
	@$(REPOCTL) handover

map: python-check
	@$(REPOCTL) map

garden: python-check
	@$(REPOCTL) garden

sync: python-check
	@$(REPOCTL) sync

issue: python-check
	@$(REPOCTL) issue $(if $(WAL),--wal "$${WAL}",) $(if $(TITLE),--title "$${TITLE}",) $(if $(BODY),--body-file "$${BODY}",) $(if $(TYPE),--type "$${TYPE}",) $(if $(PRIORITY),--priority "$${PRIORITY}",) $(if $(AREA),--area "$${AREA}",) $(if $(TOPIC),--topic "$${TOPIC}",) $(if $(STATUS),--status "$${STATUS}",) $(if $(SURFACE),--surface "$${SURFACE}",) $(if $(GATE),--gate "$${GATE}",) $(if $(filter 1 yes true,$(PUBLIC_REVIEWED)),--public-reviewed,) $(if $(REVIEW_EVIDENCE),--review-evidence "$${REVIEW_EVIDENCE}",)

review-packet: python-check
	$(if $(ISSUE_FILE),,$(error Name the issue: ISSUE_FILE=path))
	@$(REPOCTL) review-packet $(if $(ISSUE_FILE),--issue-file "$${ISSUE_FILE}",)

incident: python-check
	$(if $(TITLE),,$(error Title it: make incident TITLE="..." SUMMARY="..."))
	$(if $(SUMMARY),,$(error Summarize it: SUMMARY="..."))
	@$(REPOCTL) incident $(if $(TITLE),--title "$${TITLE}",) $(if $(SUMMARY),--summary "$${SUMMARY}",) $(if $(filter 1 yes true,$(PUBLIC_SAFE)),--public-safe,) $(if $(REVIEW_EVIDENCE),--review-evidence "$${REVIEW_EVIDENCE}",)

init: python-check
	$(if $(NAME),,$(error Name the project: make init NAME=my-project KIND=web))
	$(if $(KIND),,$(error Give its kind: make init NAME=my-project KIND=web))
	@$(REPOCTL) init $(if $(NAME),--name "$${NAME}",) $(if $(KIND),--kind "$${KIND}",) $(if $(OWNER),--owner "$${OWNER}",)

adopt: python-check
	$(if $(NAME),,$(error Name the project: make -f <kit>/Makefile adopt NAME=my-app KIND=web OWNER=you))
	$(PYTHON) "$(KIT_DIR)/tools/repoctl.py" --root "$(CURDIR)" adopt --from "$(KIT_DIR)" --name "$${NAME}" --kind "$${KIND}" $(if $(OWNER),--owner "$${OWNER}",)

kit-update: python-check
	@$(REPOCTL) kit-update $(if $(KIT),--kit "$${KIT}",)

check: python-check
	@$(REPOCTL) check

doctor: python-check
	@$(REPOCTL) doctor

readiness: python-check
	@$(REPOCTL) readiness

inventory: python-check
	@$(REPOCTL) inventory

resources: python-check
	@$(REPOCTL) resources

skill-digest: python-check
	$(if $(SKILL_PATH),,$(error Name the skill: SKILL_PATH=.agents/skills/name))
	@$(REPOCTL) skill-digest "$${SKILL_PATH}"

validate: python-check
	$(if $(BODY),,$(error Name the body: BODY=path))
	@$(REPOCTL) validate-issue $(if $(BODY),--body-file "$${BODY}",) $(if $(STATUS),--status "$${STATUS}",)

labels: python-check
	@$(REPOCTL) labels --sync

github-sync: python-check
	@$(REPOCTL) github-sync

eval: python-check
	@$(REPOCTL) eval $(if $(AGENT),--host "$${AGENT}",) $(if $(TASKS),--tasks "$${TASKS}",) $(if $(MODEL),--model "$${MODEL}",)

trial: python-check
	$(if $(NAME),,$(error Name a request in .agents/trials/: make trial NAME=waypoint))
	@$(REPOCTL) trial "$${NAME}" $(if $(MODEL),--model "$${MODEL}",) $(if $(BUDGET),--budget "$${BUDGET}",)

help: python-check
	@$(REPOCTL) help
# </repoctl:commands>

# Project-specific targets live in project.mk, so this Makefile stays the kit's and kit-update can refresh it.
-include project.mk
