"""Generate host adapter files from host-neutral canonical sources.

Canonical content lives in `.agents/` (skills, agent roles, MCP routes), read
through kit/registry.py. A host directory such as `.claude/` receives only
generated redirect stubs plus hook wiring for capabilities of enabled packs,
so there is one copy of every instruction and any agent can read the canonical
tree. kit/derive.py writes them (`make sync`); `make check` fails on drift or
stray files.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

from .core import RepoctlError, load_project
from .gitinfo import is_repository
from .registry import ROLE_ACCESS, ROLE_TIERS, Registry, yaml_string  # noqa: F401 - re-exported for scaffold

GENERATED_MARK = "Generated by repoctl adapters"
GENERATED_NOTE = "<!-- Generated by repoctl adapters from {source}. Do not edit; edit the source. -->"


# --- Claude Code -----------------------------------------------------------

CLAUDE_MODELS = {"fast": "haiku", "balanced": "sonnet", "deep": "opus", "inherit": "inherit"}
CLAUDE_TOOLS = {
    "read-only": "Read, Grep, Glob, Bash",
    "docs-only": "Read, Grep, Glob, Bash, Edit, Write",
    # web and full roles inherit every tool, including configured MCP servers.
}
HOOK = '"$CLAUDE_PROJECT_DIR/tools/repoctl" hook {event}'  # launcher picks Python 3.11+
CLAUDE_ALLOWED_COMMANDS = [
    "make start", "make next", "make ui-review", "make done", "make check", "make test", "make verify", "make map",
    "make where:*", "make garden", "make risk", "make capabilities", "make sync", "make handover",
    "make inventory", "make resources", "make similar:*", "make new:*",
]


def claude_settings(root: Path) -> tuple[dict[str, str], dict[str, str], list[str]]:
    """Model map, tool map, and command allowlist; project.toml [adapters.claude] overrides."""
    adapters_table = load_project(root).get("adapters", {})
    claude = adapters_table.get("claude", {}) if isinstance(adapters_table, dict) else {}
    claude = claude if isinstance(claude, dict) else {}
    models = {**CLAUDE_MODELS, **claude.get("models", {})}
    tools = {**CLAUDE_TOOLS, **claude.get("tools", {})}
    allow = list(claude.get("allow", CLAUDE_ALLOWED_COMMANDS))
    return models, tools, allow


def render_claude(root: Path) -> dict[str, str]:
    files: dict[str, str] = {}
    models, tools, allow = claude_settings(root)
    registry = Registry(root)
    for skill in registry.of("skill"):
        source = skill.path
        files[f".claude/skills/{skill.name}/SKILL.md"] = (
            f"---\nname: {skill.name}\ndescription: {yaml_string(skill.description)}\n---\n"
            f"{GENERATED_NOTE.format(source=source)}\n\n"
            f"Read [`{source}`](../../../{source}) and follow it. Resolve its relative paths "
            f"from `.agents/skills/{skill.name}/`.\n"
        )
    for role in registry.of("agent"):
        source = role.path
        access, tier = role.fields["access"], role.fields["tier"]
        header = [f"name: {role.name}", f"description: {yaml_string(role.description)}"]
        if access in tools:
            header.append(f"tools: {tools[access]}")
        header.append(f"model: {models[tier]}")
        files[f".claude/agents/{role.name}.md"] = (
            "---\n" + "\n".join(header) + "\n---\n"
            f"{GENERATED_NOTE.format(source=source)}\n\n"
            f"You are the `{role.name}` role. Read `{source}` (your canonical role) and "
            "`docs/delegation.md` (the brief and report contract) before acting, then do the "
            "task in your brief and answer only in the report format they define.\n"
        )
    routes = [route for route in registry.of("mcp") if route.fields.get("enabled", False)]
    settings = {
        "$schema": "https://json.schemastore.org/claude-code-settings.json",
        "hooks": {
            "SessionStart": [{"hooks": [{"type": "command", "command": HOOK.format(event="session-start")}]}],
            "PreCompact": [{"hooks": [{"type": "command", "command": HOOK.format(event="pre-compact")}]}],
            "PostToolUse": [
                {
                    "matcher": "Edit|Write|MultiEdit|NotebookEdit",
                    "hooks": [{"type": "command", "command": HOOK.format(event="after-edit")}],
                }
            ],
            "Stop": [{"hooks": [{"type": "command", "command": HOOK.format(event="stop")}]}],
        },
        "permissions": {"allow": [f"Bash({command})" for command in allow]},
    }
    # MCP servers are deliberately not pre-approved here: Claude Code asks the
    # user once per project server, which keeps consent with the person.
    files[".claude/settings.json"] = json.dumps(settings, indent=2) + "\n"
    servers: dict[str, object] = {}
    for route in routes:
        spec = route.fields
        headers = {name: f"${{{variable}:-}}" for name, variable in spec.get("env_headers", {}).items()}
        if spec["transport"] == "http":
            server: dict[str, object] = {"type": "http", "url": spec["url"]}
            if headers:
                server["headers"] = headers
        else:
            command = list(spec["command"])
            server = {"command": command[0], "args": command[1:]}
        servers[route.name] = server
    # Always rendered (even empty) so disabling every route also clears the host config.
    files[".mcp.json"] = json.dumps({"mcpServers": servers}, indent=2) + "\n"
    return files


HOSTS = {"claude": render_claude}
HOST_OWNED_PREFIXES = {"claude": (".claude/", ".mcp.json")}


def configured_hosts(root: Path) -> list[str]:
    adapters = load_project(root).get("adapters", {})  # no table: no generated hosts
    hosts = adapters.get("hosts", []) if isinstance(adapters, dict) else []
    unknown = [host for host in hosts if host not in HOSTS]
    if unknown:
        raise RepoctlError(f"adapters.hosts has unsupported hosts: {', '.join(unknown)} (supported: {', '.join(HOSTS)})")
    return list(hosts)


def render(root: Path) -> dict[str, str]:
    files: dict[str, str] = {}
    for host in configured_hosts(root):
        files.update(HOSTS[host](root))
    return files


def host_files(root: Path, hosts: list[str]) -> list[str]:
    """Files present in host-owned locations, excluding git-ignored local state."""
    found: list[str] = []
    for host in hosts:
        for prefix in HOST_OWNED_PREFIXES[host]:
            target = root / prefix
            if prefix.endswith("/") and target.is_dir():
                found += [path.relative_to(root).as_posix() for path in target.rglob("*") if path.is_file()]
            elif target.is_file():
                found.append(prefix)
    if found and is_repository(root):
        ignored = subprocess.run(
            ["git", "-C", str(root), "check-ignore", "--stdin"],
            input="\n".join(found), capture_output=True, text=True, check=False,
        ).stdout.split()
        found = [path for path in found if path not in set(ignored)]
    return sorted(found)
