"""Generate host adapter files from host-neutral canonical sources.

Canonical content lives in `.agents/skills/*/SKILL.md`, `.agents/agents/*.md`,
and the `[[mcp]]` routes in `resources.toml`. A host directory such as
`.claude/` receives only generated redirect stubs plus hook wiring, so there
is one copy of every instruction and any agent can read the canonical tree.
kit/derive.py writes them (`make sync`); `make check` fails on drift or stray files.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError as error:  # pragma: no cover - exercised on Python 3.10
    raise SystemExit("repoctl requires Python 3.11 or newer") from error

from .core import RepoctlError, ensure_inside_root, load_project
from .gitinfo import is_repository

FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
MAX_DESCRIPTION = 1024  # host skill catalogs truncate or reject longer descriptions
BLOCK_SCALAR = re.compile(r"[>|][+-]?")
ROLE_ACCESS = {"read-only", "docs-only", "web", "full"}
ROLE_TIERS = {"fast", "balanced", "deep", "inherit"}
PINNED_PACKAGE = re.compile(r"@\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$|==\d+(?:\.\d+)*$")
GENERATED_MARK = "Generated by repoctl adapters"
GENERATED_NOTE = "<!-- Generated by repoctl adapters from {source}. Do not edit; edit the source. -->"


def frontmatter(text: str) -> dict[str, str]:
    """Parse flat YAML frontmatter: plain, quoted, and folded/literal block scalars."""
    match = FRONTMATTER.match(text)
    if not match:
        return {}
    values: dict[str, str] = {}
    lines = match.group(1).splitlines()
    index = 0
    while index < len(lines):
        line = lines[index]
        index += 1
        key, separator, value = line.partition(":")
        if not separator or line.startswith((" ", "\t")):
            continue
        key, value = key.strip(), value.strip()
        if BLOCK_SCALAR.fullmatch(value):
            block = []
            while index < len(lines) and (not lines[index].strip() or lines[index].startswith((" ", "\t"))):
                block.append(lines[index].strip())
                index += 1
            joiner = "\n" if value.startswith("|") else " "
            values[key] = joiner.join(part for part in block if part).strip()
            continue
        if value[:1] in {"'", '"'}:
            values[key] = value[1:-1] if len(value) > 1 and value[-1] == value[0] else value
            continue
        if ": " in value:
            raise RepoctlError(f"frontmatter value for {key} contains ': '; quote it so every host parses it as YAML")
        values[key] = value
    return values


def yaml_string(value: str) -> str:
    """A double-quoted scalar (JSON strings are valid YAML) on a single line."""
    return json.dumps(" ".join(value.split()), ensure_ascii=False)


def canonical_skills(root: Path) -> list[dict[str, str]]:
    skills = []
    for skill_file in sorted((root / ".agents" / "skills").glob("*/SKILL.md")):
        text = skill_file.read_text(encoding="utf-8")
        values = frontmatter(text)
        name = skill_file.parent.name
        if values.get("name") != name or not values.get("description"):
            raise RepoctlError(f"{skill_file.relative_to(root).as_posix()} needs name: {name} and a description")
        if len(values["description"]) > MAX_DESCRIPTION:
            raise RepoctlError(f"{skill_file.relative_to(root).as_posix()} description exceeds {MAX_DESCRIPTION} characters")
        skills.append({"name": name, "description": values["description"]})
    return skills


def canonical_roles(root: Path) -> list[dict[str, str]]:
    roles = []
    for role_file in sorted((root / ".agents" / "agents").glob("*.md")):
        if role_file.name == "README.md":
            continue
        relative = role_file.relative_to(root).as_posix()
        values = frontmatter(role_file.read_text(encoding="utf-8"))
        name = role_file.stem
        if values.get("name") != name or not values.get("description"):
            raise RepoctlError(f"{relative} needs name: {name} and a description")
        if values.get("access") not in ROLE_ACCESS:
            raise RepoctlError(f"{relative} access must be one of {', '.join(sorted(ROLE_ACCESS))}")
        if values.get("tier") not in ROLE_TIERS:
            raise RepoctlError(f"{relative} tier must be one of {', '.join(sorted(ROLE_TIERS))}")
        roles.append(values)
    return roles


def mcp_routes(root: Path) -> list[dict[str, object]]:
    """Validated `[[mcp]]` routes from the resource registry."""
    project = load_project(root)
    resources = project.get("resources", {})
    registry_value = resources.get("registry", "resources.toml") if isinstance(resources, dict) else "resources.toml"
    registry_path = ensure_inside_root(root, root / str(registry_value), "resource registry")
    if not registry_path.is_file():
        return []
    with registry_path.open("rb") as registry_file:
        routes = tomllib.load(registry_file).get("mcp", [])
    errors = []
    seen: set[str] = set()
    for position, route in enumerate(routes, start=1):
        identifier = route.get("id")
        label = f"mcp route {identifier or position}"
        if not isinstance(identifier, str) or not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", identifier):
            errors.append(f"mcp route #{position} id must be kebab-case")
        elif identifier in seen:
            errors.append(f"duplicate mcp route id: {identifier}")
        seen.add(str(identifier))
        if not isinstance(route.get("purpose"), str) or not route["purpose"].strip():
            errors.append(f"{label} needs a purpose")
        transport = route.get("transport")
        if transport == "http":
            url = route.get("url")
            if not isinstance(url, str) or not url.startswith("https://") or "?" in url:
                errors.append(f"{label} url must be HTTPS without query parameters (keys go in env headers)")
        elif transport == "stdio":
            command = route.get("command")
            if not isinstance(command, list) or not command or not all(isinstance(part, str) for part in command):
                errors.append(f"{label} command must be a non-empty string array")
            elif command[0] in {"npx", "uvx", "pipx"} and not any(PINNED_PACKAGE.search(part) for part in command[1:]):
                errors.append(f"{label} must pin its package to an exact version")
        else:
            errors.append(f"{label} transport must be http or stdio")
        headers = route.get("env_headers", {})
        if not isinstance(headers, dict) or not all(
            isinstance(value, str) and re.fullmatch(r"[A-Z][A-Z0-9_]*", value) for value in headers.values()
        ):
            errors.append(f"{label} env_headers must map header names to UPPER_CASE environment variable names")
    if errors:
        raise RepoctlError("mcp routes check failed:\n- " + "\n- ".join(errors))
    return routes


# --- Claude Code -----------------------------------------------------------

CLAUDE_MODELS = {"fast": "haiku", "balanced": "sonnet", "deep": "opus", "inherit": "inherit"}
CLAUDE_TOOLS = {
    "read-only": "Read, Grep, Glob, Bash",
    "docs-only": "Read, Grep, Glob, Bash, Edit, Write",
    # web and full roles inherit every tool, including configured MCP servers.
}
HOOK = 'python3 "$CLAUDE_PROJECT_DIR/tools/repoctl.py" hook {event}'
CLAUDE_ALLOWED_COMMANDS = [
    "make start", "make done", "make finish", "make check", "make test", "make verify", "make map",
    "make where:*", "make garden", "make risk", "make capabilities", "make sync", "make handover",
    "make inventory", "make resources", "make similar:*", "make new:*",
]


def claude_settings(root: Path) -> tuple[dict[str, str], dict[str, str], list[str]]:
    """Model map, tool map, and command allowlist; project.toml [adapters.claude] overrides."""
    adapters_table = load_project(root).get("adapters", {})
    claude = adapters_table.get("claude", {}) if isinstance(adapters_table, dict) else {}
    claude = claude if isinstance(claude, dict) else {}
    models = {**CLAUDE_MODELS, **claude.get("models", {})}
    tools = {**CLAUDE_TOOLS, **claude.get("tools", {})}
    allow = list(claude.get("allow", CLAUDE_ALLOWED_COMMANDS))
    return models, tools, allow


def render_claude(root: Path) -> dict[str, str]:
    files: dict[str, str] = {}
    models, tools, allow = claude_settings(root)
    for skill in canonical_skills(root):
        source = f".agents/skills/{skill['name']}/SKILL.md"
        files[f".claude/skills/{skill['name']}/SKILL.md"] = (
            f"---\nname: {skill['name']}\ndescription: {yaml_string(skill['description'])}\n---\n"
            f"{GENERATED_NOTE.format(source=source)}\n\n"
            f"Read [`{source}`](../../../{source}) and follow it. Resolve its relative paths "
            f"from `.agents/skills/{skill['name']}/`.\n"
        )
    for role in canonical_roles(root):
        source = f".agents/agents/{role['name']}.md"
        header = [f"name: {role['name']}", f"description: {yaml_string(role['description'])}"]
        if role["access"] in tools:
            header.append(f"tools: {tools[role['access']]}")
        header.append(f"model: {models[role['tier']]}")
        files[f".claude/agents/{role['name']}.md"] = (
            "---\n" + "\n".join(header) + "\n---\n"
            f"{GENERATED_NOTE.format(source=source)}\n\n"
            f"You are the `{role['name']}` role. Read `{source}` (your canonical role) and "
            "`docs/delegation.md` (the brief and report contract) before acting, then do the "
            "task in your brief and answer only in the report format they define.\n"
        )
    routes = [route for route in mcp_routes(root) if route.get("enabled", False)]
    settings = {
        "$schema": "https://json.schemastore.org/claude-code-settings.json",
        "hooks": {
            "SessionStart": [{"hooks": [{"type": "command", "command": HOOK.format(event="session-start")}]}],
            "PreCompact": [{"hooks": [{"type": "command", "command": HOOK.format(event="pre-compact")}]}],
            "PostToolUse": [
                {
                    "matcher": "Edit|Write|MultiEdit|NotebookEdit",
                    "hooks": [{"type": "command", "command": HOOK.format(event="after-edit")}],
                }
            ],
            "Stop": [{"hooks": [{"type": "command", "command": HOOK.format(event="stop")}]}],
        },
        "permissions": {"allow": [f"Bash({command})" for command in allow]},
    }
    # MCP servers are deliberately not pre-approved here: Claude Code asks the
    # user once per project server, which keeps consent with the person.
    files[".claude/settings.json"] = json.dumps(settings, indent=2) + "\n"
    servers: dict[str, object] = {}
    for route in routes:
        headers = {name: f"${{{variable}:-}}" for name, variable in route.get("env_headers", {}).items()}
        if route["transport"] == "http":
            server: dict[str, object] = {"type": "http", "url": route["url"]}
            if headers:
                server["headers"] = headers
        else:
            command = list(route["command"])
            server = {"command": command[0], "args": command[1:]}
        servers[str(route["id"])] = server
    # Always rendered (even empty) so disabling every route also clears the host config.
    files[".mcp.json"] = json.dumps({"mcpServers": servers}, indent=2) + "\n"
    return files


HOSTS = {"claude": render_claude}
HOST_OWNED_PREFIXES = {"claude": (".claude/", ".mcp.json")}


def configured_hosts(root: Path) -> list[str]:
    adapters = load_project(root).get("adapters", {})  # no table: no generated hosts
    hosts = adapters.get("hosts", []) if isinstance(adapters, dict) else []
    unknown = [host for host in hosts if host not in HOSTS]
    if unknown:
        raise RepoctlError(f"adapters.hosts has unsupported hosts: {', '.join(unknown)} (supported: {', '.join(HOSTS)})")
    return list(hosts)


def render(root: Path) -> dict[str, str]:
    files: dict[str, str] = {}
    for host in configured_hosts(root):
        files.update(HOSTS[host](root))
    return files


def host_files(root: Path, hosts: list[str]) -> list[str]:
    """Files present in host-owned locations, excluding git-ignored local state."""
    found: list[str] = []
    for host in hosts:
        for prefix in HOST_OWNED_PREFIXES[host]:
            target = root / prefix
            if prefix.endswith("/") and target.is_dir():
                found += [path.relative_to(root).as_posix() for path in target.rglob("*") if path.is_file()]
            elif target.is_file():
                found.append(prefix)
    if found and is_repository(root):
        ignored = subprocess.run(
            ["git", "-C", str(root), "check-ignore", "--stdin"],
            input="\n".join(found), capture_output=True, text=True, check=False,
        ).stdout.split()
        found = [path for path in found if path not in set(ignored)]
    return sorted(found)
