"""What the kit ships into a project and how the project records it.

The leaf under `init`, `adopt`, and `kit-update`: the SHA-256 lock
(`tools/kit-lock.json`), the project's local form of each kit file (Markdown
localized to pruned material, `kit.mk` with renamed targets), and the
helpers that decide both. Nothing here writes derived files, so it imports
none of the modules that do.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
from pathlib import Path

from .core import RepoctlError, load_project, repository_files
from .gitinfo import git, path_matches
from .names import DESIGN, ERROR_LOG, HANDOVER, STACK_DECISION, VISION

LOCK = "tools/kit-lock.json"
MAKE_TARGET = re.compile(r"(?m)^([A-Za-z0-9][A-Za-z0-9_.-]*)\s*:(?!=)")


def colliding_targets(project_makefile: str, kit_makefile: str) -> list[str]:
    ours = set(MAKE_TARGET.findall(project_makefile)) - {".PHONY"}
    return sorted(name for name in set(MAKE_TARGET.findall(kit_makefile)) & ours if not name.startswith("."))


def renamed_targets(root: Path) -> list[str]:
    """The kit targets this project runs as `kit-<name>`: the one table behind every kit-authored
    mention. Read from the files (the project's Makefile defines <name>, `kit.mk` defines `kit-<name>`),
    so adopt, `make sync`, and the session brief cannot disagree about it."""
    try:
        ours = set(MAKE_TARGET.findall((root / "Makefile").read_text(encoding="utf-8")))
        kit = set(MAKE_TARGET.findall((root / "kit.mk").read_text(encoding="utf-8")))
    except OSError:
        return []
    return sorted(name for name in ours - kit if not name.startswith(".") and f"kit-{name}" in kit)


RENAMED_TEXT = (".md", ".toml", ".yml", ".yaml", ".json")  # kit prose and config that names `make <target>`


def rename_mentions(text: str, names: list[str]) -> str:
    """`make <name>` becomes `make kit-<name>` in prose, allowlists, and generated text."""
    for name in names:
        text = re.sub(rf"\bmake {re.escape(name)}(?![\w-])", f"make kit-{name}", text)
    return text


def rename_kit_targets(project_makefile: str, kit_text: str) -> str:
    """Kit targets the project's Makefile already defines become kit-<name>, wherever they are named."""
    renamed = colliding_targets(project_makefile, kit_text)
    text = kit_text
    for name in renamed:
        word = re.escape(name)
        text = re.sub(rf"(?m)^{word}(\s*:(?!=))", rf"kit-{name}\1", text)
        text = re.sub(rf"(\$\(MAKE\)\s+){word}\b", rf"\1kit-{name}", text)
        text = re.sub(rf"\bmake {word}\b", f"make kit-{name}", text)

    def prerequisites(match: re.Match[str]) -> str:
        names = [f"kit-{token}" if token in renamed else token for token in match.group(2).split()]
        return match.group(1) + " ".join(names)

    return re.sub(r"(?m)^([A-Za-z0-9.][\w.-]*\s*:(?!=)[ \t]*)([^\n#]*)", prerequisites, text)


def render_kit_makefile(project_makefile: str, kit_makefile: str) -> str:
    """kit.mk for a project with its own Makefile: kit targets it already defines become kit-<name>."""
    # The project's default goal stays the project's.
    text = re.sub(r"(?m)^\.DEFAULT_GOAL\s*:?=.*\n", "", kit_makefile)
    text = rename_kit_targets(project_makefile, text)
    return "# Agent kit targets (AGENTS.md). Generated by `make adopt`; colliding targets are kit-<name>.\n" + text


COVERS = re.compile(r"<!--\s*covers:([^>]*?)-->")
LINK = re.compile(r"(\]\()([^)\s]+)(\))")


def localize_text(relative: str, text: str, pruned: set[str], prune: list[str], source: str) -> str:
    """A kit Markdown file as a project should have it: links to pruned template material point at
    the template source, and covers patterns that only named pruned material are dropped.
    Used by make init, make adopt, and make kit-update, so all three agree."""
    def absolute(match: re.Match[str]) -> str:
        target = match.group(2)
        if "://" in target or target.startswith("#"):
            return match.group(0)
        path, _, anchor = target.partition("#")
        resolved = os.path.normpath(os.path.join(os.path.dirname(relative), path)).replace(os.sep, "/")
        if resolved not in pruned or not source:
            return match.group(0)
        return f"{match.group(1)}{source}/blob/main/{resolved}{'#' + anchor if anchor else ''}{match.group(3)}"

    text = LINK.sub(absolute, text)
    prefixes = [pattern.removesuffix("**").rstrip("/") for pattern in prune]
    covers = COVERS.search(text)
    if covers:
        patterns = covers.group(1).split()
        kept = [p for p in patterns if not any(p == prefix or p.startswith(prefix + "/") for prefix in prefixes)]
        if kept != patterns:
            text = text[:covers.start()] + (f"<!-- covers: {' '.join(kept)} -->" if kept else "") + text[covers.end():]
    return text


# Never kit files: the project's identity, decisions, product docs, and generated output.
PROJECT_OWNED = (
    LOCK, "project.toml", VISION, "README.md", "LICENSE", "CONTEXT.md", ".gitignore", "project.mk",
    STACK_DECISION, "docs/README.md", DESIGN, ERROR_LOG,
    "docs/architecture/**", "docs/product/**", "docs/adr/**", "docs/incidents/**", ".security/**",
    ".claude/**", ".mcp.json", HANDOVER,
)


DERIVED_BLOCK = re.compile(rb"(?s)(<!-- repoctl:([a-z-]+) -->).*?(<!-- /repoctl:\2 -->)")
MAKE_BLOCK = re.compile(rb"(?ms)(^# <repoctl:([a-z-]+)>\n).*?(^# </repoctl:\2>)")


def normalized(content: bytes) -> bytes:
    """Content without generated blocks (make sync owns those), so regenerated tables are not your edits."""
    return MAKE_BLOCK.sub(rb"\1\3", DERIVED_BLOCK.sub(rb"\1\3", content))


def digest_bytes(content: bytes) -> str:
    return hashlib.sha256(normalized(content)).hexdigest()


def digest(path: Path) -> str:
    return digest_bytes(path.read_bytes())


def kit_paths(kit: Path) -> list[str]:
    """Files the template ships as kit, excluding project-owned and template-only material."""
    template = load_project(kit).get("template", {})
    prune = list(template.get("prune", [])) if isinstance(template, dict) else []
    return [path for path in repository_files(kit) if (kit / path).is_file()
            and not any(path_matches(path, pattern) for pattern in (*PROJECT_OWNED, *prune))]


AGENTS_MERGE = "adopted-agents"  # marker name of the project part inside a merged AGENTS.md
_AGENTS_PART = re.compile(rb"(?s)<!-- repoctl:" + AGENTS_MERGE.encode() + rb" -->\n(.*)<!-- /repoctl:" + AGENTS_MERGE.encode() + rb" -->")
AGENTS_HEADING = (b"\n## Project contract (your AGENTS.md from before the kit, kept verbatim)\n\n"
                  b"Owned by the project: `make kit-update` refreshes only the router above this heading.\n\n")


def merge_agents(router: bytes, project: bytes) -> bytes:
    """The kit router first, the project's own file verbatim beneath it between markers (the markers
    exclude it from the kit hash, so only the router part is ever refreshed)."""
    tail = b"" if project.endswith(b"\n") else b"\n"
    return (router.rstrip(b"\n") + b"\n" + AGENTS_HEADING + b"<!-- repoctl:" + AGENTS_MERGE.encode() + b" -->\n"
            + project + tail + b"<!-- /repoctl:" + AGENTS_MERGE.encode() + b" -->\n")


def project_agents_part(content: bytes) -> bytes | None:
    found = _AGENTS_PART.search(content)
    return found.group(1) if found else None


def _kit_version(kit: Path) -> str:
    return (git(kit, "rev-parse", "HEAD") or "").strip() or "unknown"


def project_path(root: Path, path: str) -> str:
    """Where a kit file lives in this project: adopted projects keep the kit Makefile as kit.mk and
    colliding workflows as kit-<name>."""
    if path == "Makefile" and (root / "kit.mk").is_file():
        return "kit.mk"
    if path.startswith(".github/workflows/"):
        renamed = str(Path(path).with_name("kit-" + Path(path).name))
        if (root / renamed).is_file():
            return renamed
    return path


def write_lock(root: Path, kit: Path, paths: list[str] | None = None, kept: list[str] = (),
               merged: dict[str, str] | None = None) -> None:
    """Record what the project now has from the kit (init and adopt). `kept` are the project's own files
    at kit paths (make adopt never overwrites them); only the kit's version of those is remembered."""
    shipped = paths if paths is not None else kit_paths(kit)
    files = {path: digest(root / project_path(root, path)) for path in shipped if (root / project_path(root, path)).is_file()}
    _save_lock(root, _kit_version(kit), files, {path: digest_bytes(_new_content(kit, root, path)) for path in kept},
               merged=merged)


def _save_lock(root: Path, version: str, files: dict[str, str], kept: dict[str, str],
               bases: dict[str, str] | None = None, merged: dict[str, str] | None = None) -> None:
    previous = read_lock(root) if (root / LOCK).is_file() else {}
    if version == "unknown" and previous.get("kit_version") not in (None, "none", "unknown"):
        version = str(previous["kit_version"])  # a non-git kit checkout does not erase a known version
    data: dict[str, object] = {"kit_version": version, "files": dict(sorted(files.items()))}
    if kept:
        data["kept"] = dict(sorted(kept.items()))
    if merged:  # kit files that hold the project's own content too (AGENTS.md): only the kit part is refreshed
        data["merged"] = dict(sorted(merged.items()))
    if bases:  # conflicted files: the version they had from the kit before the project's edit
        data["bases"] = dict(sorted(bases.items()))
    (root / LOCK).parent.mkdir(parents=True, exist_ok=True)
    (root / LOCK).write_text(json.dumps(data, indent=1) + "\n", encoding="utf-8")


def read_lock(root: Path) -> dict[str, object]:
    try:
        data = json.loads((root / LOCK).read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {"kit_version": "none", "files": {}}
    except json.JSONDecodeError as error:
        raise RepoctlError(f"{LOCK} is not valid JSON: {error}") from error
    if not isinstance(data.get("files"), dict):
        raise RepoctlError(f"{LOCK} needs a files table")
    return data


def _new_content(kit: Path, root: Path, path: str, merged: dict[str, str] | None = None) -> bytes:
    """The kit file as this project should have it (kit.mk is regenerated with the project's renames;
    a merged file keeps the project's part as it is now)."""
    if path == "Makefile" and project_path(root, path) == "kit.mk":
        ours = (root / "Makefile").read_text(encoding="utf-8") if (root / "Makefile").is_file() else ""
        return render_kit_makefile(ours, (kit / path).read_text(encoding="utf-8")).encode()
    if path.endswith(".md"):  # the same localization make init applied when the project was made, plus adopt's target renames
        template = load_project(kit).get("template", {})
        prune = list(template.get("prune", [])) if isinstance(template, dict) else []
        pruned = {file for file in repository_files(kit) if any(path_matches(file, pattern) for pattern in prune)}
        source = str(template.get("source", "")).rstrip("/") if isinstance(template, dict) else ""
        text = localize_text(path, (kit / path).read_text(encoding="utf-8"), pruned, prune, source)
        router = rename_mentions(text, renamed_targets(root)).encode()
        if merged and path in merged:
            current = (root / path).read_bytes() if (root / path).is_file() else b""
            part = project_agents_part(current)
            if part is not None:
                return merge_agents(router, part)
        return router
    content = (kit / path).read_bytes()
    if path.endswith(RENAMED_TEXT):
        try:
            return rename_mentions(content.decode("utf-8"), renamed_targets(root)).encode()
        except UnicodeDecodeError:
            pass
    return content
