"""Portable session lifecycle: what happens at start, before compaction, after an
edit, and before an agent declares it is done.

Hosts with hooks call `repoctl hook <event>` (Claude Code via the generated
`.claude/settings.json`); hosts without hooks run `make start` and
`make done`. Every event reads optional host JSON on stdin and never needs it.
Output is evidence about the repository, not new authority: AGENTS.md rules.
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

from . import derive, docsync, hygiene
from .core import RepoctlError, governance_profile, load_project, read_text_file, repository_files
from .garden import self_heal_errors
from .gitinfo import branch, branch_paths, changed_paths, git, head
from .navigate import print_map
from .product import next_step, product_summary
from .risk import assess
from .uireview import review_status

HANDOVER_LIMIT = 4000
CHECKPOINT = ".agent/checkpoint.md"
MAP_LIMIT = 15
STATE = ".agent/hook-state.json"
CANONICAL_INPUTS = (".agents/skills/", ".agents/agents/", "resources.toml", "project.toml")


def read_event() -> dict[str, object]:
    if sys.stdin is None or sys.stdin.isatty():
        return {}
    try:
        data = json.loads(sys.stdin.read() or "{}")
    except (json.JSONDecodeError, OSError, UnicodeDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def _relative(root: Path, value: object) -> str | None:
    if not isinstance(value, str) or not value:
        return None
    path = Path(value)
    try:
        return (path if path.is_absolute() else root / path).resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return None


def _heal_derived(root: Path) -> list[str]:
    try:
        return derive.sync(root)
    except (RepoctlError, OSError) as error:
        return [f"adapter regeneration failed: {error}"]


def session_start(root: Path) -> None:
    project = load_project(root)
    changed = changed_paths(root)
    print("# Session brief (generated by `repoctl hook session-start`; repository facts, AGENTS.md rules)")
    print(
        f"{project.get('name')} · phase={project.get('phase')} · profile={governance_profile(project)} · "
        f"branch {branch(root)} @ {head(root)} · {len(changed)} uncommitted path(s)"
    )
    recent = (git(root, "log", "-5", "--format=- %h %s") or "").strip()
    if recent:
        print("\nRecent commits:\n" + recent)
    handover = read_text_file(root, "HANDOVER.md")
    if handover:
        clipped = handover[:HANDOVER_LIMIT] + ("\n… (truncated; read HANDOVER.md)" if len(handover) > HANDOVER_LIMIT else "")
        print("\n## HANDOVER.md (read first; verify against the working tree)\n" + clipped)
    if (root / CHECKPOINT).is_file():
        print(f"\nPre-compaction checkpoint available: {CHECKPOINT}")
    healed = _heal_derived(root)
    hooks_note = install_git_hooks(root)
    print()
    print_map(root, limit=MAP_LIMIT)
    try:
        findings = self_heal_errors(root, project)
    except Exception as error:  # noqa: BLE001 - the brief must survive a broken manifest
        findings = [str(error)]
    if healed:
        findings.insert(0, "regenerated derived files: " + ", ".join(healed))
    if hooks_note:
        findings.insert(0, hooks_note)
    try:
        step = next_step(root)
        print(f"\n## Next step ({step['phase']})\n{step['action']}\nHow: {step['guide']}. Done when: {step['verify']}.")
    except Exception as error:  # noqa: BLE001 - the brief must survive a malformed feature list
        print(f"\n## Next step\nmake next failed: {error}")
    print("\n## Needs attention")
    print("\n".join(f"- {item}" for item in findings[:15]) or "- nothing: the self-healing checks are green")
    print(
        "\n## Working agreement\n"
        "- You orchestrate and keep the goal; delegate bounded searches, builds, reviews, and doc fixes to the roles\n"
        "  in .agents/agents/ using the brief in docs/delegation.md. Subagent reports must stay short and cite file:line.\n"
        "- Navigate with `make where Q=\"...\"` before broad searching; `make risk` sets the ceremony for your change.\n"
        "- Before declaring done: update the docs that cover what you changed, then `make done`."
        "\n- Missing a capability? `make similar Q=\"...\"`, then `make new` (skill, agent role, or doc) wires it in."
    )


def pre_compact(root: Path) -> None:
    changed = changed_paths(root)
    doc_bindings = docsync.bindings(root, repository_files(root))
    pending = docsync.pending_documents(doc_bindings, changed)
    lines = [
        "# Pre-compaction checkpoint",
        "",
        f"Written: {datetime.now(timezone.utc).isoformat(timespec='seconds')} on branch {branch(root)} @ {head(root)}.",
        "Compare with `git status`; update HANDOVER.md with goal, decisions, and next action if the work continues.",
        "",
        "## Uncommitted paths",
        *(f"- {path}" for path in changed[:60]),
        "",
        "## Documents that still need updating",
        *([f"- {doc} (covers {', '.join(paths[:5])})" for doc, paths in pending.items()] or ["- none"]),
    ]
    target = root / CHECKPOINT
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"checkpoint written to {CHECKPOINT}")


HANDOVER_TEMPLATE = "docs/handoffs/TEMPLATE.md"


def write_handover(root: Path) -> str:
    """Create root HANDOVER.md from the one template with git facts pre-filled."""
    target = root / "HANDOVER.md"
    if target.exists():
        return "HANDOVER.md already exists; update it in place (it is never overwritten)."
    template = read_text_file(root, HANDOVER_TEMPLATE)
    if template is None:
        raise RepoctlError(f"{HANDOVER_TEMPLATE} is missing")
    changed = changed_paths(root)
    owed = docsync.pending_documents(docsync.bindings(root, repository_files(root)), changed)
    facts = {
        "`<timestamp>`": datetime.now(timezone.utc).isoformat(timespec="minutes"),
        "`<branch/commit or issue links>`": f"`{branch(root)}` @ `{head(root)}`",
        "`<clean or exact uncommitted paths>`": ", ".join(f"`{path}`" for path in changed[:20]) or "clean",
    }
    text = re.sub(r"(?m)^<!-- index:.*-->\n\n?", "", template)
    for placeholder, value in facts.items():
        text = text.replace(placeholder, value, 1)
    if owed:
        text += "\n## Documents still owed\n\n" + "\n".join(f"- {doc} (covers {', '.join(paths[:4])})" for doc, paths in owed.items()) + "\n"
    target.write_text(text, encoding="utf-8")
    return "Wrote HANDOVER.md (ignored). Fill in objective, decisions, blockers, and the exact next action."


def _load_state(root: Path, session: str) -> dict[str, list[str]]:
    try:
        state = json.loads((root / STATE).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        state = {}
    return state if isinstance(state, dict) and state.get("session") == session else {"session": session, "noted": []}


def after_edit(root: Path, event: dict[str, object]) -> None:
    tool_input = event.get("tool_input") if isinstance(event.get("tool_input"), dict) else {}
    relative = _relative(root, tool_input.get("file_path") or tool_input.get("notebook_path"))
    if not relative:
        return
    notes = []
    if relative.startswith(".claude/") or relative == ".mcp.json":
        notes.append(f"{relative} is generated. Put the change in .agents/ or resources.toml; `make sync` regenerates it.")
    elif relative.startswith(CANONICAL_INPUTS) or relative.endswith(".md"):
        healed = _heal_derived(root)
        if healed:
            notes.append("Derived files regenerated from their sources: " + ", ".join(healed))
    session = str(event.get("session_id", "local"))
    state = _load_state(root, session)
    owned = [doc for doc in docsync.owners(docsync.bindings(root, repository_files(root)), relative) if doc not in state["noted"]]
    if owned:
        notes.append(f"{relative} is documented by {', '.join(owned)}; keep it true in this change (the stop gate checks).")
        state["noted"] = sorted(set(state["noted"]) | set(owned))
        (root / STATE).parent.mkdir(parents=True, exist_ok=True)
        (root / STATE).write_text(json.dumps(state), encoding="utf-8")
    if notes:
        print(json.dumps({"hookSpecificOutput": {"hookEventName": "PostToolUse", "additionalContext": " ".join(notes)}}))


def finish_findings(root: Path) -> list[str]:
    """Fast completion gate over this branch's change set (commits since the base plus uncommitted)."""
    repository = load_project(root).get("repository", {})
    base = str(repository.get("default_branch", "main")) if isinstance(repository, dict) else "main"
    changed = branch_paths(root, base)
    if not changed:
        return []
    files = repository_files(root)
    doc_bindings = docsync.bindings(root, files)
    owed = docsync.owed_documents(root, doc_bindings, base, changed_paths(root))
    findings = [
        f"{doc} covers changed {', '.join(paths[:4])}{' …' if len(paths) > 4 else ''} but was not updated"
        " (update it, or record why in the commit with a 'Docs-Unaffected: <doc> <reason>' trailer)"
        for doc, paths in owed.items()
    ]
    findings += derive.drift(root)
    findings += docsync.dead_bindings(doc_bindings, files)
    present = [path for path in changed if path in set(files)]
    findings += hygiene.scan_markers(root, present).errors
    findings += review_status(root)
    return findings


SCISSORS = re.compile(r"(?m)^# -+ >8 -+$")
GATE_BLOCKED = 3  # distinct from crashes, which .githooks/commit-msg lets through


def commit_gate(root: Path, message_file: str | None) -> int:
    """git commit-msg gate over the staged change set; returns the exit code."""
    staged = [path for path in (git(root, "diff", "--cached", "--name-only") or "").splitlines() if path]
    if not staged:
        return 0
    try:
        message = Path(message_file).read_text(encoding="utf-8") if message_file else ""
    except OSError:
        message = ""
    # Like git's cleanup: drop everything below the `commit -v` scissors line, then comments.
    message = SCISSORS.split(message, maxsplit=1)[0]
    message = "\n".join(line for line in message.splitlines() if not line.startswith("#"))
    exempt = docsync.exemption_scope(docsync.message_trailers(root, message)) or set()
    files = repository_files(root)
    doc_bindings = docsync.bindings(root, files)
    # A merge commit brings in commits that already passed this gate or recorded a
    # Docs-Unaffected decision; re-asking would re-litigate it. make done and CI's
    # stale-document check still read those commits' trailers.
    merging = git(root, "rev-parse", "-q", "--verify", "MERGE_HEAD") is not None
    findings = [] if merging else [
        f"{doc} covers staged {', '.join(paths[:4])} but is not staged"
        for doc, paths in docsync.pending_documents(doc_bindings, staged).items()
        if "*" not in exempt and doc not in exempt
    ]
    # Derived drift only matters when this commit touches a source of derived files.
    if any(path.startswith(CANONICAL_INPUTS) or path.endswith(".md") for path in staged):
        findings += derive.drift(root)
    findings += hygiene.scan_markers(root, [path for path in staged if path in set(files)]).errors
    if not findings:
        return 0
    print("Commit blocked by the self-healing gate (docs/self-healing.md):", file=sys.stderr)
    print("\n".join(f"- {item}" for item in findings[:15]), file=sys.stderr)
    print(
        "Owed doc: update and stage it, or add the trailer 'Docs-Unaffected: <doc> <reason>'\n"
        "  in the message's LAST paragraph (with any Co-Authored-By lines), as git requires.\n"
        "Derived file: run make sync and stage the result. Marker: fix the named line.",
        file=sys.stderr,
    )
    return GATE_BLOCKED


def install_git_hooks(root: Path) -> str | None:
    """Point git at .githooks only when that cannot disable hooks already in use."""
    if not (root / ".githooks" / "commit-msg").is_file() or git(root, "rev-parse", "--git-dir") is None:
        return None
    if (git(root, "config", "--get", "core.hooksPath") or "").strip():
        return None
    hooks_dir = (git(root, "rev-parse", "--git-path", "hooks") or "").strip()
    existing = sorted(
        path.name for path in (root / hooks_dir).glob("*")
        if hooks_dir and path.is_file() and not path.name.endswith(".sample")
    )
    if existing:
        return (
            f"git commit gate NOT installed: .git/hooks already has {', '.join(existing)}; call "
            "`.githooks/commit-msg \"$1\"` from your commit-msg hook (or hook manager) to add it"
        )
    if git(root, "config", "core.hooksPath", ".githooks") is None:
        return None
    return "installed git hooks (core.hooksPath=.githooks): commits now run the self-healing gate"


def stop(root: Path, event: dict[str, object]) -> None:
    if event.get("stop_hook_active"):
        return  # the agent already continued once because of this gate
    findings = finish_findings(root)
    if findings:
        reason = "Self-healing gate before stopping:\n" + "\n".join(f"- {item}" for item in findings[:12])
        reason += "\nFix these (delegate doc work to the doc-gardener role if large), or explain to the user why they stay."
        print(json.dumps({"decision": "block", "reason": reason}))


def finish(root: Path) -> int:
    findings = finish_findings(root)
    tier, _ = assess(root)
    print(f"Change risk tier: {tier} (details: make risk)")
    if findings:
        print("Not finished:\n" + "\n".join(f"- {item}" for item in findings))
        return 1
    print("Self-healing gate passed for this branch's change set.")
    summary = product_summary(root)
    if summary:
        print(summary)
    return 0


def run_hook(root: Path, event_name: str, message_file: str | None = None) -> int:
    if event_name == "commit-msg":
        try:
            return commit_gate(root, message_file)
        except Exception as error:  # noqa: BLE001 - a broken kit must not wedge git
            print(f"repoctl hook commit-msg skipped: {type(error).__name__}: {error}", file=sys.stderr)
            return 0
    event = read_event()
    handlers = {
        "session-start": lambda: session_start(root),
        "pre-compact": lambda: pre_compact(root),
        "after-edit": lambda: after_edit(root, event),
        "stop": lambda: stop(root, event),
    }
    try:
        handlers[event_name]()
    except Exception as error:  # noqa: BLE001 - a hook must never fail the host session
        print(f"repoctl hook {event_name}: {type(error).__name__}: {error}", file=sys.stderr)
    return 0
