"""Portable session lifecycle: what happens at start, before compaction, after an
edit, and before an agent declares it is done.

Hosts with hooks call `repoctl hook <event>` (Claude Code via the generated
`.claude/settings.json`); hosts without hooks run `make start` and
`make done`. Every event reads optional host JSON on stdin and never needs it.
Output is evidence about the repository, not new authority: AGENTS.md rules.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

from . import derive, docsync, hygiene
from .core import RepoctlError, default_branch, governance_profile, load_project, read_text_file, repository_files
from .garden import self_heal_errors
from .gitinfo import branch, branch_paths, changed_paths, committed_paths, git, head, path_matches
from .names import HANDOVER
from .navigate import print_map
from .product import next_step, product_summary
from .registry import Registry, project_plugin_files
from .risk import assess, classify, tier_rules
from .uireview import review_status


def _product_on(root: Path) -> bool:
    try:
        return Registry(root).pack_state.get("product", False)
    except RepoctlError:
        return True  # a broken manifest is reported by the checks; keep the product guidance

HANDOVER_LIMIT = 4000
CHECKPOINT = ".agent/checkpoint.md"
MAP_LIMIT = 15
STATE = ".agent/hook-state.json"
CANONICAL_INPUTS = (".agents/", "tools/kit/commands.py", "project.toml")
CRITIC_RECORD = ".agent/critic.md"
CRITIC_VERDICTS = ("blocker", "ship-with-residuals")


def read_event() -> dict[str, object]:
    if sys.stdin is None or sys.stdin.isatty():
        return {}
    try:
        data = json.loads(sys.stdin.read() or "{}")
    except (json.JSONDecodeError, OSError, UnicodeDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def _relative(root: Path, value: object) -> str | None:
    if not isinstance(value, str) or not value:
        return None
    path = Path(value)
    try:
        return (path if path.is_absolute() else root / path).resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return None


def _heal_derived(root: Path) -> list[str]:
    try:
        return derive.sync(root)
    except (RepoctlError, OSError) as error:
        return [f"adapter regeneration failed: {error}"]


def _digest(root: Path, path: str) -> str:
    try:
        return hashlib.sha256((root / path).read_bytes()).hexdigest()
    except OSError:
        return "deleted"


def _snapshot(root: Path, paths: list[str]) -> dict[str, str]:
    return {path: _digest(root, path) for path in paths}


def _record_snapshot(root: Path, session: str, changed: list[str]) -> None:
    """Remember what was already dirty, so the stop gate can tell this session's edits apart."""
    state = _load_state(root, session)
    if "snapshot" in state:
        return  # a resumed or compacted session keeps its original baseline
    state["snapshot"] = _snapshot(root, changed)
    state["snapshot_head"] = (git(root, "rev-parse", "HEAD") or "").strip()
    (root / STATE).parent.mkdir(parents=True, exist_ok=True)
    (root / STATE).write_text(json.dumps(state), encoding="utf-8")


def session_changes(root: Path, session: str) -> list[str] | None:
    """Dirty paths whose content differs from the session-start snapshot; None without a snapshot."""
    state = _load_state(root, session)
    snapshot = state.get("snapshot")
    if not isinstance(snapshot, dict):
        return None
    start = str(state.get("snapshot_head", ""))
    committed: list[str] = []
    if start:
        if git(root, "merge-base", "--is-ancestor", start, "HEAD") is None:
            return None  # the start commit is gone or not an ancestor: judge the whole tree
        committed = (git(root, "diff", "--name-only", f"{start}..HEAD") or "").splitlines()
    dirty = [path for path in changed_paths(root) if snapshot.get(path) != _digest(root, path)]
    return sorted(path for path in set(dirty) | set(committed) if path and not path.startswith(".agent/"))  # .agent/ is hook scratch


def session_start(root: Path, event: dict[str, object] | None = None) -> None:
    project = load_project(root)
    changed = changed_paths(root)
    try:
        _record_snapshot(root, str((event or {}).get("session_id", "local")), changed)
    except OSError:
        pass  # without a baseline the stop gate falls back to the whole change set
    print("# Session brief (generated by `repoctl hook session-start`; repository facts, AGENTS.md rules)")
    print(
        f"{project.get('name')} · phase={project.get('phase')} · profile={governance_profile(project)} · "
        f"branch {branch(root)} @ {head(root)} · {len(changed)} uncommitted path(s)"
    )
    recent = (git(root, "log", "-5", "--format=- %h %s") or "").strip()
    if recent:
        print("\nRecent commits:\n" + recent)
    handover = read_text_file(root, HANDOVER)
    if handover:
        clipped = handover[:HANDOVER_LIMIT] + ("\n… (truncated; read HANDOVER.md)" if len(handover) > HANDOVER_LIMIT else "")
        print("\n## HANDOVER.md (read first; verify against the working tree)\n" + clipped)
    if (root / CHECKPOINT).is_file():
        print(f"\nPre-compaction checkpoint available: {CHECKPOINT}")
    healed = _heal_derived(root)
    hooks_note = install_git_hooks(root)
    print()
    print_map(root, limit=MAP_LIMIT)
    try:
        findings = self_heal_errors(root, project)
    except Exception as error:  # noqa: BLE001 - the brief must survive a broken manifest
        findings = [str(error)]
    if healed:
        findings.insert(0, "regenerated derived files: " + ", ".join(healed))
    if hooks_note:
        findings.insert(0, hooks_note)
    try:
        if _product_on(root):
            step = next_step(root)
            print(f"\n## Next step ({step['phase']})\n{step['action']}\nHow: {step['guide']}. Done when: {step['verify']}.")
    except Exception as error:  # noqa: BLE001 - the brief must survive a malformed feature list
        print(f"\n## Next step\nmake next failed: {error}")
    try:
        plugins = project_plugin_files(root)
    except OSError:
        plugins = []
    if plugins:  # plugins run on every repoctl command and hook: say which ones exist
        print("\n## Project plugins (executed by every repoctl command)\n" + "\n".join(f"- {path}" for path in plugins))
    print("\n## Needs attention")
    print("\n".join(f"- {item}" for item in findings[:15]) or "- nothing: the self-healing checks are green")
    print(
        "\n## Working agreement\n"
        "- You orchestrate and keep the goal; hand a subtask that needs its own context or independence (the critic)\n"
        "  to the roles in .agents/agents/, and do everything else directly. Each role fixes the brief it takes and the\n"
        "  block it returns; reports stay short and cite file:line.\n"
        "- The critic returns one verdict, `blocker` or `ship-with-residuals`; save that block verbatim to\n"
        f"  {CRITIC_RECORD}, which `make done` reads before a high-risk change set can be called done.\n"
        "- Navigate with `make where Q=\"...\"` before broad searching; `make risk` sets the ceremony for your change.\n"
        "- Before declaring done: update the docs that cover what you changed, then `make done`."
        "\n- Missing a capability? `make similar Q=\"...\"`, then `make new KIND=...` (skill, agent, doc, rule, check,"
        "\n  command, mcp, or pack) wires it in; outside tools go through the skill-scout role first."
    )


def pre_compact(root: Path) -> None:
    changed = changed_paths(root)
    doc_bindings = docsync.bindings(root, repository_files(root))
    pending = docsync.pending_documents(doc_bindings, changed)
    lines = [
        "# Pre-compaction checkpoint",
        "",
        f"Written: {datetime.now(timezone.utc).isoformat(timespec='seconds')} on branch {branch(root)} @ {head(root)}.",
        "Compare with `git status`; update HANDOVER.md with goal, decisions, and next action if the work continues.",
        "",
        "## Uncommitted paths",
        *(f"- {path}" for path in changed[:60]),
        "",
        "## Documents that still need updating",
        *([f"- {doc} (covers {', '.join(paths[:5])})" for doc, paths in pending.items()] or ["- none"]),
    ]
    target = root / CHECKPOINT
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"checkpoint written to {CHECKPOINT}")


HANDOVER_TEMPLATE = "docs/handoffs/TEMPLATE.md"


def write_handover(root: Path) -> str:
    """Create root HANDOVER.md from the one template with git facts pre-filled."""
    target = root / HANDOVER
    if target.exists():
        return "HANDOVER.md already exists; update it in place (it is never overwritten)."
    template = read_text_file(root, HANDOVER_TEMPLATE)
    if template is None:
        raise RepoctlError(f"{HANDOVER_TEMPLATE} is missing")
    changed = changed_paths(root)
    owed = docsync.pending_documents(docsync.bindings(root, repository_files(root)), changed)
    facts = {
        "`<timestamp>`": datetime.now(timezone.utc).isoformat(timespec="minutes"),
        "`<branch/commit or issue links>`": f"`{branch(root)}` @ `{head(root)}`",
        "`<clean or exact uncommitted paths>`": ", ".join(f"`{path}`" for path in changed[:20]) or "clean",
    }
    text = re.sub(r"(?m)^<!-- index:.*-->\n\n?", "", template)
    for placeholder, value in facts.items():
        text = text.replace(placeholder, value, 1)
    if owed:
        text += "\n## Documents still owed\n\n" + "\n".join(f"- {doc} (covers {', '.join(paths[:4])})" for doc, paths in owed.items()) + "\n"
    target.write_text(text, encoding="utf-8")
    return "Wrote HANDOVER.md (ignored). Fill in objective, decisions, blockers, and the exact next action."


def _load_state(root: Path, session: str) -> dict:
    try:
        state = json.loads((root / STATE).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        state = {}
    return state if isinstance(state, dict) and state.get("session") == session else {"session": session, "noted": []}


def after_edit(root: Path, event: dict[str, object]) -> None:
    tool_input = event.get("tool_input") if isinstance(event.get("tool_input"), dict) else {}
    relative = _relative(root, tool_input.get("file_path") or tool_input.get("notebook_path"))
    if not relative:
        return
    notes = []
    if relative.startswith(".claude/") or relative == ".mcp.json":
        notes.append(f"{relative} is generated. Put the change in .agents/; `make sync` regenerates it.")
    elif relative.startswith(CANONICAL_INPUTS) or relative.endswith(".md"):
        healed = _heal_derived(root)
        if healed:
            notes.append("Derived files regenerated from their sources: " + ", ".join(healed))
    session = str(event.get("session_id", "local"))
    state = _load_state(root, session)
    owned = [doc for doc in docsync.owners(docsync.bindings(root, repository_files(root)), relative) if doc not in state["noted"]]
    if owned:
        notes.append(f"{relative} is documented by {', '.join(owned)}; keep it true in this change (the stop gate checks).")
    # Scoped rules arrive when they apply, once per session, instead of living in the router.
    rules = [rule for rule in Registry(root).of("rule")
             if rule.path not in state["noted"] and any(path_matches(relative, pattern) for pattern in rule.fields["scope"])]
    for rule in rules:
        notes.append(f"Rule for {relative}: {rule.description} ({rule.path}).")
    if owned or rules:
        state["noted"] = sorted(set(state["noted"]) | set(owned) | {rule.path for rule in rules})
        (root / STATE).parent.mkdir(parents=True, exist_ok=True)
        (root / STATE).write_text(json.dumps(state), encoding="utf-8")
    if notes:
        print(json.dumps({"hookSpecificOutput": {"hookEventName": "PostToolUse", "additionalContext": " ".join(notes)}}))


def critic_findings(root: Path, project: dict[str, object], base: str, only: list[str] | None = None) -> list[str]:
    """High-risk work needs an independent critic whose verdict this gate can read.

    The record is the critic's return saved verbatim to `.agent/critic.md`; a
    verdict outside the fixed vocabulary is a failure, not a softer pass.
    """
    if governance_profile(project) == "minimal":
        return []  # the host owns issues, review, and ceremony
    rules = tier_rules(project)
    if only is not None and not any(classify(path, rules) == "high" for path in only):
        return []  # a session scope demands evidence only for high-risk work it changed
    risky = [path for path in committed_paths(root, base) if classify(path, rules) == "high"]
    if not risky:
        return []
    vocabulary = " | ".join(CRITIC_VERDICTS)
    content = read_text_file(root, CRITIC_RECORD) or ""
    if not content.strip():
        return [
            f"high-risk change ({', '.join(risky[:4])}) has no critic evidence: run the critic role on this change"
            f" set and save its return verbatim to {CRITIC_RECORD}"
        ]
    verdict = re.search(r"(?im)^Verdict:\s*(\S+)", content)
    if verdict is None:
        return [f"{CRITIC_RECORD} states no verdict; the critic returns exactly one of: {vocabulary}"]
    word = verdict.group(1).strip().lower()
    if word not in CRITIC_VERDICTS:
        return [f"{CRITIC_RECORD} verdict {word!r} is outside the fixed vocabulary ({vocabulary}); prose is not a verdict"]
    if word == CRITIC_VERDICTS[0]:
        return [f"{CRITIC_RECORD} verdict is {word}: fix what it lists, then ask the critic again"]
    reviewed = re.search(r"(?im)^Commit:\s*([0-9a-f]{40})\b", content)
    if not reviewed:
        return [f"{CRITIC_RECORD} has no 'Commit: <40-hex>' line, so it is not bound to a reviewed change set"]
    current = (git(root, "rev-parse", "HEAD") or "").strip()
    if current and reviewed.group(1) != current:
        return [f"{CRITIC_RECORD} reviews {reviewed.group(1)[:12]}, not HEAD {current[:12]}: the critic read older work"]
    return []


def finish_findings(root: Path, session_paths: list[str] | None = None) -> list[str]:
    """Fast completion gate over this branch's change set (commits since the base plus uncommitted).

    `session_paths` narrows it to the uncommitted paths one session changed (the stop hook);
    None judges the whole change set (`finish`, `make done`).
    """
    project = load_project(root)
    base = default_branch(project)
    scoped = session_paths is not None
    changed = session_paths if session_paths is not None else branch_paths(root, base)
    if not changed:
        return []
    files = repository_files(root)
    file_set = set(files)
    doc_bindings = docsync.bindings(root, files)
    uncommitted = changed if scoped else changed_paths(root)
    owed = {} if scoped else docsync.owed_documents(root, doc_bindings, base, uncommitted)
    # Predict the commit gate too: it asks per commit, so a doc touched earlier on the
    # branch does not cover uncommitted code. Two gates that disagree cost a round trip.
    for doc, paths in docsync.pending_documents(doc_bindings, uncommitted).items():
        owed.setdefault(doc, paths)
    findings = [
        f"{doc} covers changed {', '.join(paths[:4])}{' …' if len(paths) > 4 else ''} but was not updated"
        " (update it, or record why in the commit with a 'Docs-Unaffected: <doc> <reason>' trailer)"
        for doc, paths in owed.items()
    ]
    if not scoped or any(path.startswith(CANONICAL_INPUTS) or path.endswith(".md") for path in changed):
        findings += derive.drift(root)
    findings += docsync.dead_bindings(doc_bindings, files)
    present = [path for path in changed if path in file_set]
    findings += hygiene.scan_markers(root, present).errors
    findings += critic_findings(root, project, base, session_paths)
    return findings


SCISSORS = re.compile(r"(?m)^# -+ >8 -+$")
GATE_BLOCKED = 3  # the hook blocks on any non-zero status except 126/127 (no interpreter or launcher)


def _plugin_findings(root: Path) -> list[str]:
    """A project plugin that cannot load, or a registry that cannot load, blocks the commit: the gate
    must never be skipped because the kit it runs on is broken (issue #28)."""
    try:
        errors = Registry(root).plugin_errors
    except Exception as error:  # noqa: BLE001 - an unloadable registry is itself a blocking finding
        return [f"[registry] the capability registry cannot load: {type(error).__name__}: {error} "
                "(fix it, then recommit; `git commit --no-verify` bypasses the gate, say why in the PR)"]
    return [f"[plugin-load] {path}: {error} (fix or delete the plugin file; make check shows it)" for path, error in errors]


def commit_gate(root: Path, message_file: str | None) -> int:
    """git commit-msg gate over the staged change set; returns the exit code."""
    staged = [path for path in (git(root, "diff", "--cached", "--name-only") or "").splitlines() if path]
    if not staged:
        return 0
    try:
        message = Path(message_file).read_text(encoding="utf-8") if message_file else ""
    except OSError:
        message = ""
    # Like git's cleanup: drop everything below the `commit -v` scissors line, then comments.
    message = SCISSORS.split(message, maxsplit=1)[0]
    message = "\n".join(line for line in message.splitlines() if not line.startswith("#"))
    exempt = docsync.exemption_scope(docsync.message_trailers(root, message)) or set()
    files = repository_files(root)
    file_set = set(files)
    doc_bindings = docsync.bindings(root, files)
    # A merge commit brings in commits that already passed this gate or recorded a
    # Docs-Unaffected decision; re-asking would re-litigate it. make done and CI's
    # stale-document check still read those commits' trailers.
    merged_in: set[str] = set()
    if git(root, "rev-parse", "-q", "--verify", "MERGE_HEAD") is not None:
        merged_in = set((git(root, "diff", "--name-only", "HEAD...MERGE_HEAD") or "").split())
    findings = _plugin_findings(root) + [
        f"{doc} covers staged {', '.join(paths[:4])} but is not staged"
        for doc, paths in docsync.pending_documents(doc_bindings, [p for p in staged if p not in merged_in]).items()
        if "*" not in exempt and doc not in exempt
    ]
    # Derived drift only matters when this commit touches a source of derived files.
    if any(path.startswith(CANONICAL_INPUTS) or path.endswith(".md") for path in staged):
        findings += derive.drift(root)
    findings += hygiene.scan_markers(root, [path for path in staged if path in file_set]).errors
    if not findings:
        return 0
    print("Commit blocked by the self-healing gate (docs/self-healing.md):", file=sys.stderr)
    print("\n".join(f"- {item}" for item in findings[:15]), file=sys.stderr)
    print(
        "Owed doc: update and stage it, or add the trailer 'Docs-Unaffected: <doc.md> <reason>'\n"
        "  (name the doc itself; a code path or glob such as 'tools/** untouched' exempts nothing)\n"
        "  in the message's LAST paragraph (with any Co-Authored-By lines), as git requires.\n"
        "Derived file: run make sync and stage the result. Marker: fix the named line.",
        file=sys.stderr,
    )
    return GATE_BLOCKED


def install_git_hooks(root: Path) -> str | None:
    """Point git at .githooks only when that cannot disable hooks already in use."""
    if not (root / ".githooks" / "commit-msg").is_file() or git(root, "rev-parse", "--git-dir") is None:
        return None
    if (git(root, "config", "--get", "core.hooksPath") or "").strip():
        return None
    hooks_dir = (git(root, "rev-parse", "--git-path", "hooks") or "").strip()
    existing = sorted(
        path.name for path in (root / hooks_dir).glob("*")
        if hooks_dir and path.is_file() and not path.name.endswith(".sample")
    )
    if existing:
        return (
            f"git commit gate NOT installed: .git/hooks already has {', '.join(existing)}; call "
            "`.githooks/commit-msg \"$1\"` from your commit-msg hook (or hook manager) to add it"
        )
    if git(root, "config", "core.hooksPath", ".githooks") is None:
        return None
    return "installed git hooks (core.hooksPath=.githooks): commits now run the self-healing gate"


def stop(root: Path, event: dict[str, object]) -> None:
    if event.get("stop_hook_active"):
        return  # the agent already continued once because of this gate
    findings = finish_findings(root, session_changes(root, str(event.get("session_id", "local"))))
    if findings:
        reason = "Self-healing gate before stopping:\n" + "\n".join(f"- {item}" for item in findings[:12])
        reason += "\nFix these (delegate doc work to the doc-gardener role if large), or explain to the user why they stay."
        print(json.dumps({"decision": "block", "reason": reason}))


def finish(root: Path) -> int:
    findings = finish_findings(root)
    tier, _ = assess(root)
    print(f"Change risk tier: {tier} (details: make risk)")
    if findings:
        print("Not finished:\n" + "\n".join(f"- {item}" for item in findings))
        return 1
    print("Self-healing gate passed for this branch's change set.")
    if not _product_on(root):
        return 0
    summary = product_summary(root)
    if summary:
        print(summary)
    # Advisory per change; the review gates the feature (make next) and the release (make readiness).
    for item in review_status(root):
        print(f"UI review (before the feature is done and before release): {item}")
    return 0


# The one list of hook events: `repoctl hook <event>`, its argument choices, and the dispatcher all derive from it.
HANDLERS = {
    "session-start": lambda root, event: session_start(root, event),
    "pre-compact": lambda root, event: pre_compact(root),
    "after-edit": lambda root, event: after_edit(root, event),
    "stop": lambda root, event: stop(root, event),
}
HOOK_EVENTS = (*HANDLERS, "commit-msg")


def run_hook(root: Path, event_name: str, message_file: str | None = None) -> int:
    if event_name == "commit-msg":
        try:
            return commit_gate(root, message_file)
        except Exception as error:  # noqa: BLE001 - a gate that crashed has not approved the commit
            print(f"commit blocked: the gate itself failed: {type(error).__name__}: {error} "
                  "(`git commit --no-verify` bypasses it; say why in the PR)", file=sys.stderr)
            return GATE_BLOCKED
    event = read_event()
    try:
        HANDLERS[event_name](root, event)
    except Exception as error:  # noqa: BLE001 - a hook must never fail the host session
        print(f"repoctl hook {event_name}: {type(error).__name__}: {error}", file=sys.stderr)
    return 0
